# Generated by Django 4.1.7 on 2023-04-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_servicerequest_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='city_id',
            field=models.CharField(max_length=100),
        ),
    ]
