# Generated by Django 4.1.7 on 2023-04-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_partner_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplaint',
            name='complaint',
            field=models.TextField(),
        ),
    ]
