# Generated by Django 4.1.7 on 2023-04-16 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usercomplaint_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='usercomplaint',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usercomplaint',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complaint_booking_id', to='accounts.servicerequest'),
        ),
    ]
